import {
    Archive,
    ArrowDown,
    Bars, Bookmark, BookmarkFilled, Calendar, Check, ChevronDown, ChevronLeft,
    ChevronRight, Clock, Close, Correct, Customer, Doc, Download, Edit,
    Executer,
    Eye, Filter,
    Help,
    Hotel, Info,
    Logout,
    Main,
    Minus,
    More,
    News,
    Pin,
    Plus, Profile, Redo, Remove, Report, Resend, Revoke,
    Settings,
    SortAscending,
    SortDescending, Star, StarFilled, Task, TaskAccepted, Trash, Update
} from "./@icons";

export const iconNames = {
    "hotel": Hotel,
    "calendar": Calendar,
    "plus": Plus,
    "close": Close,
    "doc": Doc,
    "more": More,
    "profile": Profile,
    "logout": Logout,
    "eye": Eye,
    "minus": Minus,
    "edit": Edit,
    "bars": Bars,
    "sort_ascending": SortAscending,
    "sort_descending": SortDescending,
    "resend": Resend,
    "revoke": Revoke,
    "clock": Clock,
    "pin": Pin,
    "bookmark": Bookmark,
    "bookmark_filled": BookmarkFilled,
    "info": Info,
    "check": Check,
    "filter": Filter,
    "correct": Correct,
    "star": Star,
    "redo": Redo,
    "remove": Remove,
    "download": Download,
    "archive": Archive,

    "arrow_down": ArrowDown,

    "trash": Trash,
    "update": Update,

    "settings": Settings,
    "news": News,
    "task": Task,
    "task_accepted": TaskAccepted,
    "main": Main,
    "help": Help,
    "customer": Customer,
    "executer": Executer,
    "report": Report,

    "star_filled": StarFilled,
    "chevron_left": ChevronLeft,
    "chevron_down": ChevronDown,
    "chevron_right": ChevronRight,
};
