version: "3.7"

services:
  www-router:
    image: ${IMAGE_ROUTER}
    ports: ["127.0.0.1:${ROUTER_PORT}:80"]
    depends_on:
      - www-landing

  www-landing:
    image: ${IMAGE_UI}
    command: "/www/ssr"
